/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int APARENTESES = 5;
  /** RegularExpression Id. */
  int FPARENTESES = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 9;
  /** RegularExpression Id. */
  int ATRIBUICAO = 10;
  /** RegularExpression Id. */
  int VIRGULA = 11;
  /** RegularExpression Id. */
  int PONTO = 12;
  /** RegularExpression Id. */
  int TIPO_INT = 13;
  /** RegularExpression Id. */
  int TIPO_STRING = 14;
  /** RegularExpression Id. */
  int TIPO_FLOAT = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int VOID = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int CONSOLE = 21;
  /** RegularExpression Id. */
  int WRITELINE = 22;
  /** RegularExpression Id. */
  int READLINE = 23;
  /** RegularExpression Id. */
  int MAIS = 24;
  /** RegularExpression Id. */
  int MENOS = 25;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 26;
  /** RegularExpression Id. */
  int DIVISAO = 27;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 28;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 29;
  /** RegularExpression Id. */
  int IGUAL_IGUAL = 30;
  /** RegularExpression Id. */
  int DIFERENTE = 31;
  /** RegularExpression Id. */
  int MAIOR = 32;
  /** RegularExpression Id. */
  int MENOR = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int TRUE = 37;
  /** RegularExpression Id. */
  int FALSE = 38;
  /** RegularExpression Id. */
  int NUMERO_REAL = 39;
  /** RegularExpression Id. */
  int NUMERO_INTEIRO = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\".\"",
    "\"int\"",
    "\"string\"",
    "\"float\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"void\"",
    "\"return\"",
    "\"Console\"",
    "\"WriteLine\"",
    "\"ReadLine\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"true\"",
    "\"false\"",
    "<NUMERO_REAL>",
    "<NUMERO_INTEIRO>",
    "<STRING>",
    "<IDENTIFICADOR>",
  };

}
