/* Compilador.java */
/* Generated By:JavaCC: Do not edit this line. Compilador.java */
public class Compilador implements CompiladorConstants {
  public static void main(String args[]) {
    try {
      // Abrindo o arquivo de teste que contém o código a ser analisado
      java.io.FileInputStream arquivo = new java.io.FileInputStream("teste.txt");
      Compilador parser = new Compilador(arquivo);
      Token t;

      System.out.println("Lendo o arquivo teste.txt...");

      // Parte 1: Analisador Léxico 
      while ((t = parser.getNextToken()).kind != EOF) {
        System.out.println("Encontrei o Token: " + t.image);
      }
      System.out.println("Leitura finalizada com sucesso!\n");

      System.out.println("=== TESTE SINTATICO ===");

      // Reinicia o parser para análise sintática
      arquivo = new java.io.FileInputStream("teste.txt");
      Compilador.ReInit(arquivo);

      // Parte 2-4: Analisador Sintático
      parser.Inicio();

      System.out.println("Analise sintatica concluida com sucesso!");

    } catch (java.io.FileNotFoundException e) {
      System.out.println("Erro: O arquivo 'teste.txt' nao foi encontrado.");
    } catch (Exception e) {
      System.out.println("Erro na analise:");
      System.out.println(e.getMessage());
    }
  }

/* ================= SINTÁTICO ================= */
/* Parte 2-4 */

/* Ponto de entrada da análise sintática */
  static final public void Inicio() throws ParseException {
    Programa();
    jj_consume_token(0);
}

/* Programa principal */
  static final public void Programa() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO_INT:
      case TIPO_STRING:
      case TIPO_FLOAT:
      case IF:
      case WHILE:
      case VOID:
      case CONSOLE:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      if (jj_2_1(3)) {
        Funcao();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPO_INT:
        case TIPO_STRING:
        case TIPO_FLOAT:{
          Declaracao();
          break;
          }
        case IF:
        case WHILE:
        case CONSOLE:
        case IDENTIFICADOR:{
          Comando();
          break;
          }
        default:
          jj_la1[1] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

/* Declaração de variáveis */
  static final public void Declaracao() throws ParseException {
    Tipo();
    jj_consume_token(IDENTIFICADOR);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      Expressao();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(PONTO_VIRGULA);
System.out.println(" [SINTATICO] -> Declaracao de variavel validada!");
}

/* Tipos de variáveis */
  static final public void Tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:{
      jj_consume_token(TIPO_INT);
      break;
      }
    case TIPO_STRING:{
      jj_consume_token(TIPO_STRING);
      break;
      }
    case TIPO_FLOAT:{
      jj_consume_token(TIPO_FLOAT);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* ===== PARTE 4: Funções ===== */

/* Declaração de função */
  static final public void Funcao() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_STRING:
    case TIPO_FLOAT:{
      Tipo();
      break;
      }
    case VOID:{
      jj_consume_token(VOID);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(APARENTESES);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO_INT:
    case TIPO_STRING:
    case TIPO_FLOAT:{
      Parametros();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(FPARENTESES);
    jj_consume_token(ACHAVES);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case CONSOLE:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
      Comando();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case RETURN:{
      Return();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(FCHAVES);
System.out.println(" [SINTATICO] -> Funcao validada com sucesso!");
}

/* Lista de parâmetros da função */
  static final public void Parametros() throws ParseException {
    Tipo();
    jj_consume_token(IDENTIFICADOR);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      jj_consume_token(VIRGULA);
      Tipo();
      jj_consume_token(IDENTIFICADOR);
    }
}

/* Comando return da função */
  static final public void Return() throws ParseException {
    jj_consume_token(RETURN);
    Expressao();
    jj_consume_token(PONTO_VIRGULA);
System.out.println(" [SINTATICO] -> Comando de retorno validado!");
}

/* Chamada de função (Sem o ponto e virgula para poder usar em contas) */
  static final public void ChamadaFuncao() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(APARENTESES);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case APARENTESES:
    case CONSOLE:
    case NOT:
    case TRUE:
    case FALSE:
    case NUMERO_REAL:
    case NUMERO_INTEIRO:
    case STRING:
    case IDENTIFICADOR:{
      Argumentos();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(FPARENTESES);
}

/* Argumentos passados em uma chamada de função */
  static final public void Argumentos() throws ParseException {
    Expressao();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VIRGULA:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      jj_consume_token(VIRGULA);
      Expressao();
    }
}

/* Comandos gerais */
  static final public void Comando() throws ParseException {
    if (jj_2_2(2)) {
      Atribuicao();
    } else if (jj_2_3(2)) {
      ChamadaFuncao();
      jj_consume_token(PONTO_VIRGULA);
System.out.println(" [SINTATICO] -> Chamada de funcao validada!");
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:{
        If();
        break;
        }
      case WHILE:{
        While();
        break;
        }
      case CONSOLE:{
        IO();
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

/* Atribuição */
  static final public void Atribuicao() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    jj_consume_token(ATRIBUICAO);
    Expressao();
    jj_consume_token(PONTO_VIRGULA);
System.out.println(" [SINTATICO] -> Atribuicao validada!");
}

/* Estruturas condicionais */
  static final public void If() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(APARENTESES);
    Expressao();
    jj_consume_token(FPARENTESES);
    jj_consume_token(ACHAVES);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case CONSOLE:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      Comando();
    }
    jj_consume_token(FCHAVES);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(ACHAVES);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IF:
        case WHILE:
        case CONSOLE:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          break label_6;
        }
        Comando();
      }
      jj_consume_token(FCHAVES);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
System.out.println(" [SINTATICO] -> Estrutura condicional (IF/ELSE) validada!");
}

/* Laço de repetição while */
  static final public void While() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(APARENTESES);
    Expressao();
    jj_consume_token(FPARENTESES);
    jj_consume_token(ACHAVES);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case CONSOLE:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_7;
      }
      Comando();
    }
    jj_consume_token(FCHAVES);
System.out.println(" [SINTATICO] -> Laco de repeticao (WHILE) validado!");
}

/* Entrada e saída */
/* Entrada e saída */
  static final public void IO() throws ParseException {
    if (jj_2_4(3)) {
      WriteLine();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CONSOLE:{
        ReadLine();
        jj_consume_token(PONTO_VIRGULA);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void WriteLine() throws ParseException {
    jj_consume_token(CONSOLE);
    jj_consume_token(PONTO);
    jj_consume_token(WRITELINE);
    jj_consume_token(APARENTESES);
    Expressao();
    jj_consume_token(FPARENTESES);
    jj_consume_token(PONTO_VIRGULA);
System.out.println(" [SINTATICO] -> Comando de saida (WriteLine) validado!");
}

  static final public void ReadLine() throws ParseException {
    jj_consume_token(CONSOLE);
    jj_consume_token(PONTO);
    jj_consume_token(READLINE);
    jj_consume_token(APARENTESES);
    jj_consume_token(FPARENTESES);
}

/* ================= EXPRESSÕES ================= */
/* Parte 2: Expressões e operadores */
  static final public 
void Expressao() throws ParseException {
    LogicalOr();
}

  static final public void LogicalOr() throws ParseException {
    LogicalAnd();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_8;
      }
      jj_consume_token(OR);
      LogicalAnd();
    }
}

  static final public void LogicalAnd() throws ParseException {
    Equality();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_9;
      }
      jj_consume_token(AND);
      Equality();
    }
}

  static final public void Equality() throws ParseException {
    Comparison();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUAL_IGUAL:
      case DIFERENTE:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUAL_IGUAL:{
        jj_consume_token(IGUAL_IGUAL);
        break;
        }
      case DIFERENTE:{
        jj_consume_token(DIFERENTE);
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Comparison();
    }
}

  static final public void Comparison() throws ParseException {
    Additive();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIOR_IGUAL:
      case MENOR_IGUAL:
      case MAIOR:
      case MENOR:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_11;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIOR:{
        jj_consume_token(MAIOR);
        break;
        }
      case MENOR:{
        jj_consume_token(MENOR);
        break;
        }
      case MAIOR_IGUAL:{
        jj_consume_token(MAIOR_IGUAL);
        break;
        }
      case MENOR_IGUAL:{
        jj_consume_token(MENOR_IGUAL);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Additive();
    }
}

  static final public void Additive() throws ParseException {
    Multiplicative();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIS:
      case MENOS:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIS:{
        jj_consume_token(MAIS);
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Multiplicative();
    }
}

  static final public void Multiplicative() throws ParseException {
    Unary();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:
      case DIVISAO:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICACAO:{
        jj_consume_token(MULTIPLICACAO);
        break;
        }
      case DIVISAO:{
        jj_consume_token(DIVISAO);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Unary();
    }
}

  static final public void Unary() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
      Unary();
      break;
      }
    case APARENTESES:
    case CONSOLE:
    case TRUE:
    case FALSE:
    case NUMERO_REAL:
    case NUMERO_INTEIRO:
    case STRING:
    case IDENTIFICADOR:{
      Primary();
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void Primary() throws ParseException {
    if (jj_2_5(2)) {
      ChamadaFuncao();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CONSOLE:{
        ReadLine();
        break;
        }
      case IDENTIFICADOR:{
        jj_consume_token(IDENTIFICADOR);
        break;
        }
      case NUMERO_INTEIRO:{
        jj_consume_token(NUMERO_INTEIRO);
        break;
        }
      case NUMERO_REAL:{
        jj_consume_token(NUMERO_REAL);
        break;
        }
      case STRING:{
        jj_consume_token(STRING);
        break;
        }
      case TRUE:{
        jj_consume_token(TRUE);
        break;
        }
      case FALSE:{
        jj_consume_token(FALSE);
        break;
        }
      case APARENTESES:{
        jj_consume_token(APARENTESES);
        Expressao();
        jj_consume_token(FPARENTESES);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_ChamadaFuncao_164_3_16()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_Atribuicao_189_3_15()) return true;
    return false;
  }

  static private boolean jj_3R_Tipo_131_3_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(13)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(15)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_WriteLine_221_3_17()
 {
    if (jj_scan_token(CONSOLE)) return true;
    if (jj_scan_token(PONTO)) return true;
    if (jj_scan_token(WRITELINE)) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_ChamadaFuncao_164_3_16()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_WriteLine_221_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_Atribuicao_189_3_15()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(ATRIBUICAO)) return true;
    return false;
  }

  static private boolean jj_3R_Funcao_140_5_18()
 {
    if (jj_3R_Tipo_131_3_19()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_Funcao_140_3_14()) return true;
    return false;
  }

  static private boolean jj_3R_ChamadaFuncao_164_3_16()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(APARENTESES)) return true;
    return false;
  }

  static private boolean jj_3R_Funcao_140_3_14()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Funcao_140_5_18()) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) return true;
    }
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(APARENTESES)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[29];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x2de000,0x25e000,0x400,0xe000,0x8e000,0xe000,0x250000,0x100000,0x800,0x200020,0x800,0x250000,0x250000,0x250000,0x20000,0x250000,0x200000,0x0,0x0,0xc0000000,0xc0000000,0x30000000,0x30000000,0x3000000,0x3000000,0xc000000,0xc000000,0x200020,0x200020,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x400,0x400,0x0,0x0,0x0,0x0,0x400,0x0,0x0,0x7f0,0x0,0x0,0x400,0x400,0x0,0x400,0x0,0x8,0x4,0x0,0x0,0x3,0x3,0x0,0x0,0x0,0x0,0x7f0,0x7e0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[5];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Compilador(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilador(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new CompiladorTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Compilador(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CompiladorTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new CompiladorTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Compilador(CompiladorTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CompiladorTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 29; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[43];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 29; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 43; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 5; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
