/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int APARENTESES = 5;
  /** RegularExpression Id. */
  int FPARENTESES = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 9;
  /** RegularExpression Id. */
  int ATRIBUICAO = 10;
  /** RegularExpression Id. */
  int VIRGULA = 11;
  /** RegularExpression Id. */
  int TIPO_INT = 12;
  /** RegularExpression Id. */
  int TIPO_STRING = 13;
  /** RegularExpression Id. */
  int TIPO_FLOAT = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int NUMERO_INTEIRO = 18;
  /** RegularExpression Id. */
  int NUMERO_REAL = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 21;
  /** RegularExpression Id. */
  int MAIS = 22;
  /** RegularExpression Id. */
  int MENOS = 23;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 24;
  /** RegularExpression Id. */
  int DIVISAO = 25;
  /** RegularExpression Id. */
  int MAIOR = 26;
  /** RegularExpression Id. */
  int MENOR = 27;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 28;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 29;
  /** RegularExpression Id. */
  int IGUAL_IGUAL = 30;
  /** RegularExpression Id. */
  int DIFERENTE = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int OR = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int CONSOLE = 35;
  /** RegularExpression Id. */
  int WRITELINE = 36;
  /** RegularExpression Id. */
  int READLINE = 37;
  /** RegularExpression Id. */
  int PONTO = 38;
  /** RegularExpression Id. */
  int VOID = 39;
  /** RegularExpression Id. */
  int RETURN = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"int\"",
    "\"string\"",
    "\"float\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "<NUMERO_INTEIRO>",
    "<NUMERO_REAL>",
    "<STRING>",
    "<IDENTIFICADOR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"Console\"",
    "\"WriteLine\"",
    "\"ReadLine\"",
    "\".\"",
    "\"void\"",
    "\"return\"",
  };

}
